### PR TITLE
chore: update git repository in projen config

### PR DESCRIPTION
**Pull request by campionfellin**
Signed-off-by: campionfellin <campionfellin@gmail.com>

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by eladb** [comment]
The build is failing because there is a discrepancy between the checked in `package.json` and the one produced by projen You need to run `yarn projen` to regenerate `package.json` and push this change.

**Comment by campionfellin** [comment]
Anti-tamper check is pretty cool!

**Comment by campionfellin** [comment]
@eladb I don't have write access 😕

**Comment by eladb** [comment]
> @eladb I don't have write access 😕

What do you mean? `projen` should be able to write

**Comment by campionfellin** [comment]
Sorry I meant to say, I can't merge this change because I don't have write access on this repository.

**Pull request merged**
